### ISSUE TITLE
Request for confirmation of dates

### ISSUE THREAD

**Issue by ghjansen** [3ainstitute/2020-application-easter-egg#4]
According to #3 the deadline for the application process was extended to September 1st, so I was wondering if the dates of the following steps (invitation of shortlisted applicants, phone interviews, etc) were also modified somehow.

The application pack has the following info:

> We will contact applicants by 5pm on 20 September 2019 and invite shortlisted applicants to the next stage.

> II. Phone interviews: 23 September – 04 October

> We will contact applicants by 5pm on 08 October and invite further shortlisted applicants to the final stage.

> III. Face to face interviews: 09 October – 24 October

> We will extend offers to undertake the 3Ai Master of Applied Cybernetics to the top-ranked candidates by 29 October 2019. Candidates will have until 9am on 06 November 2019 to formally accept the offer.

Please, can you confirm if the dates of the steps that proceed the application remains the same?

**Comment by KathyReid** [comment]
Hi @ghjansen , thanks for your inquiry.

At this stage, _only_ the application date has shifted. The dates for shortlisting, phone interviews and face to face interviews remain as stated at this time. Should these change, for example due to application volume, applicants will be notified.

Kind regards, Kathy
